####	Java	####
.PHONY : build view clean

build :
		-@chmod +x accounts.java
		-@javac accounts.java account.java

view :
		-@\less README.txt accounts.java account.java accounts

clean :
		-@\$(RM) *.class
